<?php

$env = realpath("/var/.env");
$config = parse_ini_file($env, true);


define('RUC_EMPRESA',$config["FACTURACION_RUC_EMPRESA"]);
define('AMBIENTE',$config["FACTURACION_AMBIENTE"]); //1 = PRUEBAS, 2 = PRODUCCION
define('DOCUMENTO',$config["FACTURACION_DOCUMENTO"]);
define('ESTABLECIMIENTO',$config["FACTURACION_ESTABLECIMIENTO"]);
define('PUNTO_EMISION',$config["FACTURACION_PUNTO_EMISION"]);
define('RAZON_SOCIAL',$config["FACTURACION_RAZON_SOCIAL"]);
define('NOMBRE_COMERCIAL',$config["FACTURACION_NOMBRE_COMERCIAL"]);
define('DIRECCION_MATRIZ', $config["FACTURACION_DIRECCION_MATRIZ"]);

define('SERV_VARIOS_TABERNAS',$config["FACTURACION_SERV_VARIOS_TABERNAS"]);
define('SERV_VARIOS_TABERNAS_DESCRIPCION', $config["FACTURACION_SERV_VARIOS_TABERNAS_DESCRIPCION"]);

define('ORGANIZACION_VENTA',$config["FACTURACION_ORGANIZACION_VENTA"]);
/*define('CEDULA_CAJERO', "0103900429"); //para pruebas
define('CODIGO_VENDEDOR', "1037");*/ //para pruebas
define('CEDULA_CAJERO', $config["FACTURACION_CEDULA_CAJERO"]); // para produccion
define('CODIGO_VENDEDOR', $config["FACTURACION_CODIGO_VENDEDOR"]); // para produccion
define('TIPO_TARJETA', $config["FACTURACION_TIPO_TARJETA"]); // 21-VISA/22-MASTERCARD/23-AMERICAN EXPRESS/24-DINERS
define('DISTRITO', $config["FACTURACION_DISTRITO"]);
define('SECTOR', $config["FACTURACION_SECTOR"]);

define('LIMITE_CANTIDAD_PRODUCTOS_TIPO_VEHICULO', $config["MI_PILOTO_LIMITE_CANTIDAD_PRODUCTOS_TIPO_VEHICULO"]);


