<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4emfnxy\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4emfnxy/appProdProjectContainer.php') {
    touch(__DIR__.'/Container4emfnxy.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container4emfnxy\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container4emfnxy\appProdProjectContainer(array(
    'container.build_hash' => '4emfnxy',
    'container.build_id' => '1ee66a09',
    'container.build_time' => 1565995611,
), __DIR__.\DIRECTORY_SEPARATOR.'Container4emfnxy');
