<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDa93idz\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDa93idz/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerDa93idz.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerDa93idz\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerDa93idz\appProdProjectContainer(array(
    'container.build_hash' => 'Da93idz',
    'container.build_id' => '9f35dc69',
    'container.build_time' => 1574270981,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerDa93idz');
