<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMoxywgu\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMoxywgu/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerMoxywgu.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerMoxywgu\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerMoxywgu\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Moxywgu',
    'container.build_id' => '3f8d349f',
    'container.build_time' => 1564675674,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerMoxywgu');
